style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/isindir/sops-secrets-operator
options:
  commits:
    filters:
      Type:
        - build
        - ci
        - docs
        - feat
        - fix
        - perf
        - refactor
        - style
        - test
  commit_groups:
    title_maps:
      build: Build system and external dependency changes
      ci: CI configuration changes
      docs: Documentation changes
      feat: New features
      fix: Bug fixes
      perf: Performance improvements
      refactor: Code refactoring
      style: Cosmetic changes
      test: Changes to the tests
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
